import Head from "next/head";
import Flyers from "../components/Flyers";
import Header from "../components/Header";
import HeroImage from "../components/HeroImage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />
      {/* <HeroImage/> */}
      {/* Feed */}
      <Flyers />
      {/* modal */}
    </div>
  );
}
